### ISSUE TITLE
This APP is NOT working when in background mode.

### ISSUE THREAD

**Issue by FredGuo-CN** [UNTILabs/1point5#4]
Thanks for the code. I was looking into social distancing alarm apps these days. But none of them work properly when in the background mode, especially in IOS. The business scenario is that no one will keep this kinds of APP running in foreground, when the phone go to background mode, the scan and advertising stops. Any idea that how to deal with this?

**Comment by re2005** [comment]
Hi @FredGuo-CN thanks for your question.

You're definitely right! iOS does't allow the device to emit bluetooth signal when in background mode.

 We have come to an alternative solution for this problem, we call it "Pocket Mode" basically it allow you to have your phone working as it would be locked (in background)

Please check our other repo:
https://github.com/UNTILabs/SocialDistance

There you'll find the code for Android and iOS.

Please give it a try and let me know what you think.

Cheers.

**Comment by FredGuo-CN** [comment]
Thanks for the reply. Could you please explain a lit bit more how is the "pocket mode" working, I am very interested at this? As you know that IOS will ignore the localname property and only advertising the serviceID, I have a question here that I need to specify the serviceID in my scan options, can I get more customized data without connection to the device? The Mac is random, manufacture data is Apple static, so anything I can do?

**Comment by re2005** [comment]
You can take a look into the other repo:
https://github.com/UNTILabs/SocialDistance

The entire code is there, for iOS and you may can create an issue there with your concerns, there are a few other people also working on that project that can help you.
